sudo: false
cache: bundler
language: ruby

rvm:
  - 2.4.2

matrix:
  fast_finish: true

addons:
  code_climate:
    repo_token: ee08f267b6e437b1e68aeb024266ebaa8bf4ed474490e145ce8ad113e117d9b1

before_install:
  - gem update --system 2.6.14
  - gem install bundler -v 1.15.4

script: bundle exec rake
