version: 2

jobs:
  ruby-2.1:
    docker:
      - image: circleci/ruby:2.1
    steps:
      - checkout
      - run: bundle install
      - run: rake
  ruby-2.2:
    docker:
      - image: circleci/ruby:2.2
    steps:
      - checkout
      - run: bundle install
      - run: rake
  ruby-2.3:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: bundle install
      - run: rake
  ruby-2.4:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install
      - run: rake
  ruby-2.5:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run: bundle install
      - run: rake
  jruby:
    docker:
      - image: circleci/jruby:9.1
    steps:
      - checkout
      - run: bundle install
      - run: rake

workflows:
  version: 2
  build:
    jobs:
      - ruby-2.1
      - ruby-2.2
      - ruby-2.3
      - ruby-2.4
      - ruby-2.5
      - jruby
